Never panic([Exception? exception]) {
  throw exception ?? Exception();
}
